//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace GrpcNotifier.Data
{

    public partial class Person : XPObject
    {
        string fFirstName;
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value); }
        }
        string fLastName;
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>(nameof(LastName), ref fLastName, value); }
        }
        DateTime fDOB;
        public DateTime DOB
        {
            get { return fDOB; }
            set { SetPropertyValue<DateTime>(nameof(DOB), ref fDOB, value); }
        }
        string fPhoneNumber;
        public string PhoneNumber
        {
            get { return fPhoneNumber; }
            set { SetPropertyValue<string>(nameof(PhoneNumber), ref fPhoneNumber, value); }
        }
        bool fIsLocked;
        [ColumnDbDefaultValue("((0))")]
        public bool IsLocked
        {
            get { return fIsLocked; }
            set { SetPropertyValue<bool>(nameof(IsLocked), ref fIsLocked, value); }
        }
    }

}
